import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Emmanuel Ayeniko - Media Beast Frontend Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen background-img bg-center bg-no-repeat md:pt-[3.5rem] md:pb-[3.5rem] pt-0 pb-[2.5rem] overflow-x-hidden"
        style={{
          backgroundImage: 'url("/bg.png")',
        }}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
